ALTER TABLE t_p65061780_ash_clan_manager.clans
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS emblem_url TEXT,
  ADD COLUMN IF NOT EXISTS accent_color VARCHAR(7) DEFAULT '#FF6B1A',
  ADD COLUMN IF NOT EXISTS discipline VARCHAR(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS region VARCHAR(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS discord_url TEXT,
  ADD COLUMN IF NOT EXISTS vk_url TEXT,
  ADD COLUMN IF NOT EXISTS website_url TEXT,
  ADD COLUMN IF NOT EXISTS is_open BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS min_rank VARCHAR(64) DEFAULT '',
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
